dependencies:
  # other useful packages
  - dask
  - netcdf4
  # development
  - isort
  - black
  - blackdoc
  - flake8
  # testing
  - pytest
  - pytest-cov
  - tox-conda
  # specials
  - pre-commit
  # repl
  - ipython
  - ipykernel
  # build
  - build
  - setuptools
  - setuptools-scm
  - setuptools_scm_git_archive
  - twine
  # conda specific
  - conda-build
  - anaconda-client
  - greyskull
  # doc stuff
  - sphinx
  - sphinx_rtd_theme
  - sphinx
  - recommonmark # if want markdown
  - nbsphinx # if want notebooks
  # lsp stuff
  - autoflake
  - pyls-mypy
  - pyls-black
  - pyls-isort
